name: FWCloud-Websrv CI

on: [push, pull_request]

jobs:
  test:
    name: 'FWCloud-Websrv Test'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18', '20', '22']

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache node modules
      uses: actions/cache@v4
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install dependencies
      run: npm install
    - name: Run ESLint
      if: matrix.node-version == '18' || matrix.node-version == '20'
      run: npm run lint:check
    - name: Run Prettier
      run: npm run format:check
    - name: Build FWCloud-Websrv
      run: npm run build
    - name: Run tests
      run: npm run test
      env:
        CI: true
